name:                servant-xml
version:             1.0.1.2
synopsis:            Servant support for the XML Content-Type
description:         Servant support for the Content-Type of /application\/xml/.
                     Anything with 'ToXml' and 'FromXml' instances can be automatically marshalled.
homepage:            https://github.com/fosskers/servant-xml
license:             BSD3
author:              Colin Woodbury
maintainer:          colingw@gmail.com
copyright:           2018 Colin Woodbury
category:            Web

extra-source-files:
  - README.md
  - CHANGELOG.md

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds
  - -fwarn-name-shadowing
  - -fwarn-unused-matches
  - -fwarn-incomplete-patterns
  - -fwarn-incomplete-uni-patterns

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - http-media >= 0.7 && < 0.8
  - servant >= 0.11 && < 0.15
  - xmlbf >= 0.4
  - xmlbf-xeno >= 0.1

library:
  source-dirs: src
  other-modules: []
